// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfrhbvmwqwthoxpdnode.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcmhidm13cXd0aG94cGRub2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTk3NDAsImV4cCI6MjA2NDQzNTc0MH0.DoNTp5x-wIcdZJZ6TQNc-oHk-tGVVwmW04bs-mZqRZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);